### ISSUE TITLE
RFC #1: 建立基于 Github 的开源软件耻辱柱(Hall Of Shame)，警示后来者

### ISSUE THREAD

**Issue by bestony** [osshallofshame/RFCs#1]
# 目的

- 建立耻辱柱，告诉大家这些行为为什么不好，以及哪些项目做了这些不好的行为。
- 提供一个有迹可查，不会被「公关」掉的内容渠道
- 为提出质疑的人提供完美的证据（尽可能完美，确保每一个事件有旁证）

# 内容

在@lijiangsheng1 组织的开源之商的的群内讨论的时候，我意识到，我们应该有一个耻辱柱，帮助大家记录开源项目的错误行为，警示后来者，让后来者不要做错事。同时，在搜索相关信息后，我意识到，这些信息很容易被 PR 团队进行 PR，从而让我们失去对这些历史的记忆。不过好在，有一些第三方提供的服务，可以帮助我们记录这些信息，让我们所说的话、所做的事情能有所旁证。因此，我决定发起 **Open Source Hall Of Shame**，记录这些我们认为不好的事情，并希望借助 Github 平台来长期存储。

# TODO 

- [ ] 设计数据
- [ ] 调研 archive.org 的 API 接口
- [ ] 调研 Mirror.xyz 的 API 接口，提供一个 Github 之外的可查数据平台。或定期上 Ethereum。
- [ ] 开发出一个最简单的提交记录的工具，能够自动对接 archive.org 的存档工具，将提交者提交的信息进行存档后，提交 Git History 来进行存储。

# 干活的人

-  @bestony

**Comment by bestony** [comment]
archive.org api docs: https://archive.org/services/docs/api/index.html
